"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
import environ
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Read environment variables from .env file
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)

# Quick-start development settings - unsuitable for production
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

# Application definition
INSTALLED_APPS = [
    # Custom apps
    'apps.users',
    'apps.profiles',
    'apps.posts',
    'apps.marketplace',
    'apps.gigs',
    'apps.chats',
    'apps.groups',
    'apps.notifications',
    'apps.payments',
    'apps.moderation',
    'apps.search',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    
    # Default django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be as high as possible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Database
# Use PostgreSQL configured via DATABASE_URL
DATABASES = {
    'default': env.db('DATABASE_URL')
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CORS_ALLOW_ALL_ORIGINS = DEBUG  # For ease of local development, allow all in debug mode

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'auth_register': env('AUTH_REGISTER_THROTTLE', default='5/hour'),
        'auth_login': env('AUTH_LOGIN_THROTTLE', default='10/minute'),
        'auth_verify_otp': env('AUTH_VERIFY_OTP_THROTTLE', default='10/minute'),
        'auth_resend_otp': env('AUTH_RESEND_OTP_THROTTLE', default='3/minute'),
        'auth_forgot_password': env('AUTH_FORGOT_PASSWORD_THROTTLE', default='5/hour'),
        'auth_verify_reset_code': env('AUTH_VERIFY_RESET_CODE_THROTTLE', default='10/minute'),
        'auth_reset_password': env('AUTH_RESET_PASSWORD_THROTTLE', default='5/hour'),
    },
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# ─────────────────────────────────────────────────────────────────────────────
# Feature Flags (controlled via environment variables)
# ─────────────────────────────────────────────────────────────────────────────

# Authentication providers
ENABLE_PHONE_AUTH = env.bool('ENABLE_PHONE_AUTH', default=True)
ENABLE_EMAIL_AUTH = env.bool('ENABLE_EMAIL_AUTH', default=True)

# Verification channels
ENABLE_PHONE_VERIFICATION = env.bool('ENABLE_PHONE_VERIFICATION', default=True)
ENABLE_EMAIL_VERIFICATION = env.bool('ENABLE_EMAIL_VERIFICATION', default=True)

# OAuth providers (not yet implemented)
ENABLE_GOOGLE_AUTH = env.bool('ENABLE_GOOGLE_AUTH', default=False)
ENABLE_APPLE_AUTH = env.bool('ENABLE_APPLE_AUTH', default=False)

# JWT blacklisting
ENABLE_TOKEN_BLACKLIST = env.bool('ENABLE_TOKEN_BLACKLIST', default=True)

# Login protection
FAILED_LOGIN_MAX_ATTEMPTS = env.int('FAILED_LOGIN_MAX_ATTEMPTS', default=7)
ACCOUNT_LOCK_DURATION_MINUTES = env.int('ACCOUNT_LOCK_DURATION_MINUTES', default=30)

# OTP settings
OTP_EXPIRY_MINUTES = env.int('OTP_EXPIRY_MINUTES', default=10)
OTP_MAX_ATTEMPTS = env.int('OTP_MAX_ATTEMPTS', default=5)
OTP_MAX_RESENDS = env.int('OTP_MAX_RESENDS', default=3)
OTP_RESEND_COOLDOWN_SECONDS = env.int('OTP_RESEND_COOLDOWN_SECONDS', default=60)
ENABLE_DEVELOPMENT_OTP_OUTBOX = env.bool('ENABLE_DEVELOPMENT_OTP_OUTBOX', default=DEBUG)

# Simple JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': ENABLE_TOKEN_BLACKLIST,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': env('JWT_SECRET_KEY', default=SECRET_KEY),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_TYPE_CLAIM': 'token_type',
}
